// actionTypes.ts
export const SET_AUTHENTICATION = 'SET_AUTHENTICATION';
export const SET_USER_ROLE = 'SET_USER_ROLE';
export const SET_USER_PACKAGE_TYPE = 'SET_USER_PACKAGE_TYPE';
export const SET_AVAILABLE_FEATURES = 'SET_AVAILABLE_FEATURES';
export const SET_SELECTED_ANDROID_DEVICE = 'SET_SELECTED_ANDROID_DEVICE';
export const SET_SELECTED_IOS_DEVICE = 'SET_SELECTED_IOS_DEVICE';
export const UPDATE_PREVIEW_URL = 'UPDATE_PREVIEW_URL';